SELECT * FROM PORTFOLIOPROJECT..CovidDeaths
WHERE continent IS NOT NULL
ORDER BY 3,4

--SELECT * FROM PORTFOLIOPROJECT..CovidVaccinations
--ORDER BY 3,4


--SELECT DATA THAT WE ARE GOING TO BE USING
SELECT LOCATION,DATE , TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION
FROM PORTFOLIOPROJECT..CovidDeaths
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS TOTAL DEATHS
--SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY
SELECT LOCATION,DATE , TOTAL_CASES,TOTAL_DEATHS,(total_deaths/total_cases)*100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..CovidDeaths
WHERE LOCATION LIKE '%STATES%'
AND continent IS NOT NULL
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS POPULATION
-- SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID
SELECT LOCATION,DATE , TOTAL_CASES,POPULATION,(total_cases/population)*100 AS PERCENTPOPULATIONINFECTED
FROM PORTFOLIOPROJECT..CovidDeaths
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
ORDER BY 1,2

-- LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION
SELECT LOCATION,MAX(TOTAL_CASES)AS HIGGESTINFECTIONRATE,POPULATION,MAX(total_cases/population)*100 AS PERCENTPOPULATIONINFECTED
FROM PORTFOLIOPROJECT..CovidDeaths
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
GROUP BY LOCATION,POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC

-- SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION,MAX(CAST(total_deaths AS int)) AS TOTALDEATHCOUNT
FROM PORTFOLIOPROJECT..CovidDeaths
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

-- LET'S BREAK THINGS DOWN BY CONTINENT

--SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT continent,MAX(CAST(total_deaths AS int)) AS TOTALDEATHCOUNT
FROM PORTFOLIOPROJECT..CovidDeaths
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY TOTALDEATHCOUNT DESC


-- GLOBAL NUMBERS

SELECT  SUM(new_cases) AS TOTAL_CASES,SUM(CAST(new_deaths AS INT)) AS TOTAL_DEATHS ,SUM(CAST(new_deaths AS INT))/SUM(CAST(new_deaths AS INT))*100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..CovidDeaths
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
--GROUP NY DATE
ORDER BY 1,2

-- LOOKING AT TOTAL POPULATION VS VACCINATION

SELECT DEA.continent, DEA.LOCATION,DEA.DATE ,DEA.population,VAC.new_vaccinations,
SUM(CONVERT (INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--,(ROLLINGPEOPLEVACCINATED/population)*100
FROM PORTFOLIOPROJECT..CovidDeaths  DEA
JOIN PORTFOLIOPROJECT..CovidVaccinations VAC
  ON DEA.location= VAC.location
  AND DEA.DATE= VAC.DATE
WHERE DEA.continent IS NOT NULL
ORDER BY 2,3

-- USE CTE
WITH POPVSVAC (CONTINENT, LOCATION,DATE,POPULATION,NEW_VACCINATIONS,ROLLINGPEOPLEVACCINATED)
AS
(
SELECT DEA.continent, DEA.LOCATION,DEA.DATE ,DEA.population,VAC.new_vaccinations,
SUM(CONVERT (INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--,(ROLLINGPEOPLEVACCINATED/population)*100
FROM PORTFOLIOPROJECT..CovidDeaths  DEA
JOIN PORTFOLIOPROJECT..CovidVaccinations VAC
  ON DEA.location= VAC.location
  AND DEA.DATE= VAC.DATE
WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3
)
SELECT *,(ROLLINGPEOPLEVACCINATED/population)*100
FROM POPVSVAC

-- TEMP TABLE

DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINATED NUMERIC
)
INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT DEA.continent, DEA.LOCATION,DEA.DATE ,DEA.population,VAC.new_vaccinations,
SUM(CONVERT (INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--,(ROLLINGPEOPLEVACCINATED/population)*100
FROM PORTFOLIOPROJECT..CovidDeaths  DEA
JOIN PORTFOLIOPROJECT..CovidVaccinations VAC
  ON DEA.location= VAC.location
  AND DEA.DATE= VAC.DATE
--WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3
SELECT *,(ROLLINGPEOPLEVACCINATED/population)*100
FROM #PERCENTPOPULATIONVACCINATED

--CREATING VIEW TO STORE DATA FOR LATER VISUALISATION

CREATE VIEW PERCENTPOPULATIONVACCINATED AS
SELECT DEA.continent, DEA.LOCATION,DEA.DATE ,DEA.population,VAC.new_vaccinations,
SUM(CONVERT (INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--,(ROLLINGPEOPLEVACCINATED/population)*100
FROM PORTFOLIOPROJECT..CovidDeaths  DEA
JOIN PORTFOLIOPROJECT..CovidVaccinations VAC
  ON DEA.location= VAC.location
  AND DEA.DATE= VAC.DATE
WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3

SELECT*
FROM PERCENTPOPULATIONVACCINATED
